In [1]:
import numpy as np 
import pandas as pd

In [11]:
df = pd.read_csv("data.csv")
df.head()

  Category   Price    Rating         Stock  Discount
0      NaN  5548.0  1.870322           NaN       0.0
1      NaN  3045.0  4.757798           NaN      38.0
2      NaN  4004.0       NaN      In Stock       0.0
3      NaN  4808.0  1.492085           NaN      33.0
4      NaN  1817.0       NaN  Out of Stock      23.0

In [12]:
df.isnull().sum()

Category    2748
Price        174
Rating      2050
Stock       1352
Discount     392
dtype: int64

In [13]:
df.describe()

             Price       Rating     Discount
count  4188.000000  2312.000000  3970.000000
mean   5016.970630     3.038293    24.516625
std    2839.984813     1.143074    14.347164
min     102.000000     1.000366     0.000000
25%    2628.250000     2.069490    12.000000
50%    4996.500000     3.082060    25.000000
75%    7418.000000     4.008620    37.000000
max    9999.000000     4.997818    49.000000

In [22]:
df.isnull().any()

Category    True
Price       True
Rating      True
Stock       True
Discount    True
dtype: bool

In [27]:
df['new_price']= df['Price'].fillna(df['Price'].mean())
df

     Category   Price    Rating         Stock  Discount   new_price
0         NaN  5548.0  1.870322           NaN       0.0  5548.00000
1         NaN  3045.0  4.757798           NaN      38.0  3045.00000
2         NaN  4004.0       NaN      In Stock       0.0  4004.00000
3         NaN  4808.0  1.492085           NaN      33.0  4808.00000
4         NaN  1817.0       NaN  Out of Stock      23.0  1817.00000
...       ...     ...       ...           ...       ...         ...
4357      NaN  4436.0  4.728335           NaN      49.0  4436.00000
4358        B  6236.0       NaN  Out of Stock       4.0  6236.00000
4359      NaN  3283.0       NaN  Out of Stock       9.0  3283.00000
4360        D  2999.0  4.425995           NaN      40.0  2999.00000
4361      NaN     NaN  2.184471           NaN       0.0  5016.97063

[4362 rows x 6 columns]

In [ ]:
grouped_mean_category = df.groupby('Category')['Price'].mean()
print(grouped_mean_category)

Category
A    4782.910026
B    5410.330623
C    5086.802500
D    5032.468672
Name: Price, dtype: float64

In [39]:
url = "https://www.fdic.gov/bank-failures/failed-bank-list"
df = pd.read_html(url)
df

[                                            Bank Name                City  \
 0             Community Bank and Trust - West Georgia            LaGrange
 1                   Metropolitan Capital Bank & Trust             Chicago
 2                        The Santa Anna National Bank          Santa Anna
 3                                Pulaski Savings Bank             Chicago
 4                  The First National Bank of Lindsay             Lindsay
 5               Republic First Bank dba Republic Bank        Philadelphia
 6                                       Citizens Bank            Sac City
 7                            Heartland Tri-State Bank             Elkhart
 8                                 First Republic Bank       San Francisco
 9                                      Signature Bank            New York
 10                                Silicon Valley Bank         Santa Clara
 11                                  Almena State Bank              Almena
 12                         First City Bank of Florida   Fort Walton Beach
 13                               The First State Bank       Barboursville
 14                                 Ericson State Bank             Ericson
 15                   City National Bank of New Jersey              Newark
 16                                      Resolute Bank              Maumee
 17                              Louisa Community Bank              Louisa
 18                               The Enloe State Bank              Cooper
 19                Washington Federal Bank for Savings             Chicago
 20    The Farmers and Merchants State Bank of Argonia             Argonia
 21                                Fayette County Bank          Saint Elmo
 22  Guaranty Bank, (d/b/a BestBank in Georgia & Mi...           Milwaukee
 23                                     First NBC Bank         New Orleans
 24                                      Proficio Bank  Cottonwood Heights

             State   Cert                Acquiring Institution  \
 0         Georgia  25796                          Anchor Bank
 1        Illinois  57488              First Independence Bank
 2           Texas   5520            Coleman County State Bank
 3        Illinois  28611                      Millennium Bank
 4        Oklahoma   4134               First Bank & Trust Co.
 5    Pennsylvania  27332    Fulton Bank, National Association
 6            Iowa   8758            Iowa Trust & Savings Bank
 7          Kansas  25851               Dream First Bank, N.A.
 8      California  59017            JPMorgan Chase Bank, N.A.
 9        New York  57053                  Flagstar Bank, N.A.
 10     California  24735  First–Citizens Bank & Trust Company
 11         Kansas  15426                          Equity Bank
 12        Florida  16748            United Fidelity Bank, fsb
 13  West Virginia  14361                       MVB Bank, Inc.
 14       Nebraska  18265           Farmers and Merchants Bank
 15     New Jersey  21111                      Industrial Bank
 16           Ohio  58317                   Buckeye State Bank
 17       Kentucky  58112    Kentucky Farmers Bank Corporation
 18          Texas  10716                   Legend Bank, N. A.
 19       Illinois  30570                   Royal Savings Bank
 20         Kansas  17719                          Conway Bank
 21       Illinois   1802            United Fidelity Bank, fsb
 22      Wisconsin  30003  First-Citizens Bank & Trust Company
 23      Louisiana  58302                         Whitney Bank
 24           Utah  35495                    Cache Valley Bank

          Closing Date  Fund  Sort ascending
 0         May 1, 2026                 10551
 1    January 30, 2026                 10550
 2       June 27, 2025                 10549
 3    January 17, 2025                 10548
 4    October 18, 2024                 10547
 5      April 26, 2024                 10546
 6    November 3, 2023                 10545
 7       July 28, 2023                 10544
 8         May 1, 2023                 10543
 9      March 12, 2023                 10540
 10     March 10, 2023                 10539
 11   October 23, 2020                 10538
 12   October 16, 2020                 10537
 13      April 3, 2020                 10536
 14  February 14, 2020                 10535
 15   November 1, 2019                 10534
 16   October 25, 2019                 10533
 17   October 25, 2019                 10532
 18       May 31, 2019                 10531
 19  December 15, 2017                 10530
 20   October 13, 2017                 10529
 21       May 26, 2017                 10528
 22        May 5, 2017                 10527
 23     April 28, 2017                 10526
 24      March 3, 2017                 10525  ]

In [40]:
df[0]

,Bank Name,City,State,Cert,Acquiring Institution,Closing Date,Fund Sort ascending
0,Community Bank and Trust - West Georgia,LaGrange,Georgia,25796,Anchor Bank,"May 1, 2026",10551
1,Metropolitan Capital Bank & Trust,Chicago,Illinois,57488,First Independence Bank,"January 30, 2026",10550
2,The Santa Anna National Bank,Santa Anna,Texas,5520,Coleman County State Bank,"June 27, 2025",10549
3,Pulaski Savings Bank,Chicago,Illinois,28611,Millennium Bank,"January 17, 2025",10548
4,The First National Bank of Lindsay,Lindsay,Oklahoma,4134,First Bank & Trust Co.,"October 18, 2024",10547
5,Republic First Bank dba Republic Bank,Philadelphia,Pennsylvania,27332,"Fulton Bank, National Association","April 26, 2024",10546
6,Citizens Bank,Sac City,Iowa,8758,Iowa Trust & Savings Bank,"November 3, 2023",10545
7,Heartland Tri-State Bank,Elkhart,Kansas,25851,"Dream First Bank, N.A.","July 28, 2023",10544
8,First Republic Bank,San Francisco,California,59017,"JPMorgan Chase Bank, N.A.","May 1, 2023",10543
9,Signature Bank,New York,New York,57053,"Flagstar Bank, N.A.","March 12, 2023",10540
10,Silicon Valley Bank,Santa Clara,California,24735,First–Citizens Bank & Trust Company,"March 10, 2023",10539
11,Almena State Bank,Almena,Kansas,15426,Equity Bank,"October 23, 2020",10538
12,First City Bank of Florida,Fort Walton Beach,Florida,16748,"United Fidelity Bank, fsb","October 16, 2020",10537
13,The First State Bank,Barboursville,West Virginia,14361,"MVB Bank, Inc.","April 3, 2020",10536
14,Ericson State Bank,Ericson,Nebraska,18265,Farmers and Merchants Bank,"February 14, 2020",10535
15,City National Bank of New Jersey,Newark,New Jersey,21111,Industrial Bank,"November 1, 2019",10534
16,Resolute Bank,Maumee,Ohio,58317,Buckeye State Bank,"October 25, 2019",10533
17,Louisa Community Bank,Louisa,Kentucky,58112,Kentucky Farmers Bank Corporation,"October 25, 2019",10532
18,The Enloe State Bank,Cooper,Texas,10716,"Legend Bank, N. A.","May 31, 2019",10531
19,Washington Federal Bank for Savings,Chicago,Illinois,30570,Royal Savings Bank,"December 15, 2017",10530
20,The Farmers and Merchants State Bank of Argonia,Argonia,Kansas,17719,Conway Bank,"October 13, 2017",10529
21,Fayette County Bank,Saint Elmo,Illinois,1802,"United Fidelity Bank, fsb","May 26, 2017",10528
22,"Guaranty Bank, (d/b/a BestBank in Georgia & Mi...",Milwaukee,Wisconsin,30003,First-Citizens Bank & Trust Company,"May 5, 2017",10527
23,First NBC Bank,New Orleans,Louisiana,58302,Whitney Bank,"April 28, 2017",10526
24,Proficio Bank,Cottonwood Heights,Utah,35495,Cache Valley Bank,"March 3, 2017",10525

In [42]:
df = pd.read_excel("data.xlsx")
df

    name  age
0   deep   90
1  shubo   89

In [45]:
df.to_pickle("data.pkl")
df

    name  age
0   deep   90
1  shubo   89

In [48]:
pd.read_pickle("data.pkl")

    name  age
0   deep   90
1  shubo   89